Add explicit serialVersionUID to exception classes
This ensures that unrelated changes in these exception classes don't
affect the serialized form.

The serialVersionUIDs are from v0.6.2 and were obtained with the
serialver tool [1]:

$ serialver -classpath kotlinx-datetime-jvm-0.6.2.jar:kotlin-stdlib-1.9.21.jar kotlinx.datetime.DateTimeArithmeticException kotlinx.datetime.IllegalTimeZoneException kotlinx.datetime.DateTimeFormatException kotlinx.datetime.internal.format.parser.ParseException
kotlinx.datetime.DateTimeArithmeticException:    private static final long serialVersionUID = -3207806170214997982L;
kotlinx.datetime.IllegalTimeZoneException:    private static final long serialVersionUID = 1159315966274264801L;
kotlinx.datetime.DateTimeFormatException:    private static final long serialVersionUID = 4231196759387994100L;
kotlinx.datetime.internal.format.parser.ParseException:    private static final long serialVersionUID = 5691186997393344103L;

[1] https://docs.oracle.com/en/java/javase/21/docs/specs/man/serialver.html